#Grafana (Datasource | Dashboard.)
--- 
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  selector:
    app: grafana
  type: NodePort  # Exposing as NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001  # NodePort in the range 30000–32767

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
                #  - name: GF_INSTALL_PLUGINS
              #              value: "https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app"

          volumeMounts:
               - name: grafana-datasources
                 mountPath: /etc/grafana/provisioning/datasources
               - name: dashboard-config
                 mountPath: /etc/grafana/provisioning/dashboards/dashboard.yaml
                 subPath: dashboard.yaml
               - name: dashboard-json
                 mountPath: /etc/grafana/provisioning/dashboards/json/observability-dashboard.json
                 subPath: observability-dashboard.json
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-config
          configMap:
            name: grafana-dashboard-config
        - name: dashboard-json
          configMap:
            name: grafana-dashboard-json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.observability.svc:3100
        access: proxy
        isDefault: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus.observability.svc:9090
        access: proxy
        isDefault: false
      - name: kube-state-metrics
        type: prometheus
        url: http://prometheus.observability.svc:9090
        access: proxy
        isDefault: false
      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc:3200
        access: proxy
        isDefault: false
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
  namespace: observability
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        type: file
        options:
          path: /etc/grafana/provisioning/dashboards
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-json
  namespace: observability
data:
  observability-dashboard.json: |
    {
    "annotations": {
      "list": [
        {
          "builtIn": 1,
          "datasource": {
            "type": "grafana",
            "uid": "-- Grafana --"
          },
          "enable": true,
          "hide": true,
          "iconColor": "rgba(0, 211, 255, 1)",
          "name": "Annotations & Alerts",
          "type": "dashboard"
        }
      ]
    },
    "editable": true,
    "fiscalYearStartMonth": 0,
    "graphTooltip": 0,
    "id": 1,
    "links": [],
    "panels": [
      {
        "datasource": {
          "type": "prometheus",
          "uid": "P6E9BEA4D3F394BA1"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            },
            "unit": "percentunit"
          },
          "overrides": []
        },
        "gridPos": {
          "h": 6,
          "w": 4,
          "x": 0,
          "y": 0
        },
        "id": 9,
        "options": {
          "colorMode": "value",
          "graphMode": "area",
          "justifyMode": "auto",
          "orientation": "auto",
          "percentChangeColorMode": "standard",
          "reduceOptions": {
            "calcs": [
              "lastNotNull"
            ],
            "fields": "",
            "values": false
          },
          "showPercentChange": false,
          "textMode": "auto",
          "wideLayout": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P6E9BEA4D3F394BA1"
            },
            "editorMode": "code",
            "expr": "sum(kube_pod_container_resource_requests{cluster=\"\",resource=\"cpu\"})/ sum(kube_node_status_allocatable{cluster=\"\",resource=\"cpu\"})",
            "range": true,
            "refId": "A"
          }
        ],
        "title": "Cluster CPU Requested",
        "type": "stat"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "P6E9BEA4D3F394BA1"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 6,
          "w": 4,
          "x": 4,
          "y": 0
        },
        "id": 6,
        "options": {
          "colorMode": "value",
          "graphMode": "area",
          "justifyMode": "auto",
          "orientation": "auto",
          "percentChangeColorMode": "standard",
          "reduceOptions": {
            "calcs": [
              "lastNotNull"
            ],
            "fields": "",
            "values": false
          },
          "showPercentChange": false,
          "textMode": "auto",
          "wideLayout": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P6E9BEA4D3F394BA1"
            },
            "editorMode": "code",
            "expr": "sum(kube_pod_container_status_running{namespace=~\"observability\",cluster=\"\"})",
            "legendFormat": "__auto",
            "range": true,
            "refId": "A"
          }
        ],
        "title": "container_status_running (namespace=observability)",
        "type": "stat"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "P6E9BEA4D3F394BA1"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            },
            "unit": "percentunit"
          },
          "overrides": []
        },
        "gridPos": {
          "h": 6,
          "w": 4,
          "x": 8,
          "y": 0
        },
        "id": 7,
        "options": {
          "colorMode": "value",
          "graphMode": "area",
          "justifyMode": "auto",
          "orientation": "auto",
          "percentChangeColorMode": "standard",
          "reduceOptions": {
            "calcs": [
              "lastNotNull"
            ],
            "fields": "",
            "values": false
          },
          "showPercentChange": false,
          "textMode": "auto",
          "wideLayout": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P6E9BEA4D3F394BA1"
            },
            "editorMode": "code",
            "expr": "sum(kube_pod_info{cluster=\"\"}) / sum(kube_node_status_allocatable{cluster=\"\",resource=\"pods\"})",
            "legendFormat": "__auto",
            "range": true,
            "refId": "A"
          }
        ],
        "title": "Cluster Pod Requested",
        "type": "stat"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "P6E9BEA4D3F394BA1"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 6,
          "w": 5,
          "x": 12,
          "y": 0
        },
        "id": 5,
        "options": {
          "colorMode": "value",
          "graphMode": "area",
          "justifyMode": "auto",
          "orientation": "auto",
          "percentChangeColorMode": "standard",
          "reduceOptions": {
            "calcs": [
              "lastNotNull"
            ],
            "fields": "",
            "values": false
          },
          "showPercentChange": false,
          "textMode": "auto",
          "wideLayout": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P6E9BEA4D3F394BA1"
            },
            "editorMode": "code",
            "expr": "sum(kube_deployment_status_replicas{namespace=~\"observability\",cluster=\"\"})",
            "legendFormat": "__auto",
            "range": true,
            "refId": "A"
          }
        ],
        "title": "deployment_status_replicas (namespace=observability)",
        "type": "stat"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "PBFA97CFB590B2093"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisBorderShow": false,
              "axisCenteredZero": false,
              "axisColorMode": "text",
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": 0,
              "barWidthFactor": 0.6,
              "drawStyle": "line",
              "fillOpacity": 0,
              "gradientMode": "none",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "insertNulls": false,
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "none"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 6,
          "w": 6,
          "x": 17,
          "y": 0
        },
        "id": 3,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom",
            "showLegend": true
          },
          "tooltip": {
            "hideZeros": false,
            "mode": "single",
            "sort": "none"
          }
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "disableTextWrap": false,
            "editorMode": "builder",
            "expr": "process_virtual_memory_bytes{job=\"tempo\"}",
            "fullMetaSearch": false,
            "includeNullMetadata": true,
            "legendFormat": "__auto",
            "range": true,
            "refId": "A",
            "useBackend": false
          }
        ],
        "title": "Virtual Memory",
        "type": "timeseries"
      },
      {
        "datasource": {
          "type": "loki",
          "uid": "P8E80F9AEF21F6940"
        },
        "fieldConfig": {
          "defaults": {},
          "overrides": []
        },
        "gridPos": {
          "h": 12,
          "w": 12,
          "x": 0,
          "y": 6
        },
        "id": 2,
        "options": {
          "dedupStrategy": "exact",
          "enableInfiniteScrolling": true,
          "enableLogDetails": true,
          "prettifyLogMessage": true,
          "showCommonLabels": false,
          "showLabels": false,
          "showTime": false,
          "sortOrder": "Descending",
          "wrapLogMessage": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "direction": "backward",
            "editorMode": "builder",
            "expr": "{job=\"spring-boot-app\"} |= ``",
            "queryType": "range",
            "refId": "A"
          }
        ],
        "title": "Application Logs",
        "type": "logs"
      },
      {
        "datasource": {
          "type": "tempo",
          "uid": "P214B5B846CF3925F"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "custom": {
              "align": "auto",
              "cellOptions": {
                "type": "auto"
              },
              "inspect": false
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 12,
          "w": 12,
          "x": 12,
          "y": 6
        },
        "id": 1,
        "options": {
          "cellHeight": "sm",
          "footer": {
            "countRows": false,
            "fields": "",
            "reducer": [
              "sum"
            ],
            "show": false
          },
          "showHeader": true
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "tempo",
              "uid": "P214B5B846CF3925F"
            },
            "filters": [
              {
                "id": "421054e7",
                "operator": "=",
                "scope": "span"
              },
              {
                "id": "service-name",
                "operator": "=",
                "scope": "resource",
                "tag": "service.name",
                "value": [
                  "api-tutorial"
                ],
                "valueType": "string"
              }
            ],
            "limit": 20,
            "metricsQueryType": "range",
            "queryType": "traceqlSearch",
            "refId": "A",
            "tableType": "traces"
          }
        ],
        "title": "Traces",
        "transparent": true,
        "type": "table"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "P6E9BEA4D3F394BA1"
        },
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "palette-classic"
            },
            "custom": {
              "axisBorderShow": false,
              "axisCenteredZero": false,
              "axisColorMode": "text",
              "axisLabel": "",
              "axisPlacement": "auto",
              "barAlignment": 0,
              "barWidthFactor": 0.6,
              "drawStyle": "line",
              "fillOpacity": 0,
              "gradientMode": "none",
              "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
              },
              "insertNulls": false,
              "lineInterpolation": "linear",
              "lineWidth": 1,
              "pointSize": 5,
              "scaleDistribution": {
                "type": "linear"
              },
              "showPoints": "auto",
              "spanNulls": false,
              "stacking": {
                "group": "A",
                "mode": "none"
              },
              "thresholdsStyle": {
                "mode": "off"
              }
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green"
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "gridPos": {
          "h": 9,
          "w": 24,
          "x": 0,
          "y": 18
        },
        "id": 4,
        "options": {
          "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom",
            "showLegend": true
          },
          "tooltip": {
            "hideZeros": false,
            "mode": "single",
            "sort": "none"
          }
        },
        "pluginVersion": "12.0.0",
        "targets": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "P6E9BEA4D3F394BA1"
            },
            "disableTextWrap": false,
            "editorMode": "builder",
            "expr": "kube_pod_container_status_ready{container=\"app\"}",
            "fullMetaSearch": false,
            "includeNullMetadata": true,
            "legendFormat": "__auto",
            "range": true,
            "refId": "A",
            "useBackend": false
          }
        ],
        "title": "Pod status",
        "type": "timeseries"
      }
    ],
    "preload": false,
    "refresh": "30s",
    "schemaVersion": 41,
    "tags": [],
    "templating": {
      "list": []
    },
    "time": {
      "from": "now-5m",
      "to": "now"
    },
    "timepicker": {},
    "timezone": "browser",
    "title": "Observability Dashboard",
    "uid": "basic-observability",
    "version": 1
  }

---