{
 "title": "Observability Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cluster CPU Requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"\",resource=\"cpu\"})/ sum(kube_node_status_allocatable{cluster=\"\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "container_status_running (namespace=observability)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"observability\",cluster=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Pod Requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"\"}) / sum(kube_node_status_allocatable{cluster=\"\",resource=\"pods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "deployment_status_replicas (namespace=observability)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"observability\",cluster=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"tempo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spring-boot-app\"} |= ``"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "filters": [
      { "id": "421054e7", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "api-tutorial" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Pod status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}