apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://host.docker.internal:3100/loki/api/v1/push

    scrape_configs:
      - job_name: spring-boot-app
        static_configs:
          - targets:
              - localhost
            labels:
              job: spring-boot-app
              __path__: /var/log/pods/*spring-boot-app*/*/*.log

      - job_name: container-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: container-logs
              __path__: /var/log/containers/*.log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: default
      containers:
        - name: promtail
          image: grafana/promtail:2.9.0
          args:
            - -config.file=/etc/promtail/promtail.yaml
          securityContext:
            runAsUser: 0  # Optional: helps avoid permission issues
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: positions
              mountPath: /tmp
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: positions
          emptyDir: {}