apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki' # reference to Loki datasource
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags:
          - job
          - instance
          - pod
          - namespace
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{job="$job"} |= "$traceID"'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags:
          - service.name
        queries:
          - name: 'Request Rate'
            query: 'rate(http_server_requests_seconds_count{service="$service.name"}[5m])'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
